baseURL = "https://atelier.cboulet.info/"
  languageCode = "fr-ca"
  title = "L'atelier Boulet"
  theme = "blowfish"

  [markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true

  [params]
    colorScheme = "ocean"
    defaultAppearance = "light"
    autoSwitchAppearance = true

    [params.homepage]
      layout = "background"
      showRecent = true
      showRecentItems = 6

    [params.article]
      showDate = true
      showDateOnlyInArticle = false
      showDateUpdated = false
      showAuthor = true
      showReadingTime = false
      showWordCount = false
      showEdit = false

    [params.list]
      showDate = true
      showAuthor = false
      showReadingTime = false
      showWordCount = false
      showSummary = true

  [menu]
    [[menu.main]]
      name = "Accueil"
      pageRef = "/"
      weight = 10

    [[menu.main]]
      name = "Recettes"
      pageRef = "/posts"
      weight = 20
