baseURL = "https://atelier.cboulet.info/"
defaultContentLanguage = "fr"
languageCode = "fr-CA"
title = "L'atelier Boulet"
theme = "blowfish"

  [markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true

  [params]
    colorScheme = "autumn"
    defaultAppearance = "light"
    autoSwitchAppearance = true
    copyright = "© {{ now.Format \"2006\" }} L'atelier Boulet. Tous droits réservés."

    [params.homepage]
      layout = "background"
      showRecent = true
      showRecentItems = 6

    [params.article]
      showDate = true
      showDateOnlyInArticle = false
      showDateUpdated = false
      showAuthor = true
      showReadingTime = false
      showWordCount = false
      showEdit = false

    [params.list]
      showDate = true
      showAuthor = false
      showReadingTime = false
      showWordCount = false
      showSummary = true

    [params.footer]
      showThemeAttribution = false
      showCopyright = true

  [menu]
    [[menu.main]]
      name = "Accueil"
      pageRef = "/"
      weight = 10

    [[menu.main]]
      name = "Recettes"
      pageRef = "/posts"
      weight = 20

    [[menu.main]]
      name = "À propos"
      pageRef = "/about"
      weight = 30

    [[menu.main]]
      name = "Contact"
      pageRef = "/contact"
      weight = 40
